prefix schema: <https://schema.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
# select distinct ?s
construct {
  ?s a schema:CreativeWork;
    schema:creator ?sperson;
    .
  ?sperson a schema:Person;
}
where {
  {
    values ?type {
      <https://data.rkd.nl/thesaurus/66733>
    }
    ?s <http://www.cidoc-crm.org/cidoc-crm/P2_has_type> ?type;
    optional{
      ?s <http://www.cidoc-crm.org/cidoc-crm/P108i_was_produced_by>/<http://www.cidoc-crm.org/cidoc-crm/P141i_was_assigned_by>/rdf:rest*/rdf:first/<http://www.cidoc-crm.org/cidoc-crm/P141_assigned>/<http://www.cidoc-crm.org/cidoc-crm/P14_carried_out_by> ?sperson
    }
  }
  union
  {
    values ?material {
      <https://data.rkd.nl/thesaurus/61784>
    }
    ?s <http://www.cidoc-crm.org/cidoc-crm/P45_consists_of> ?material;
    optional{
      ?s <http://www.cidoc-crm.org/cidoc-crm/P108i_was_produced_by>/<http://www.cidoc-crm.org/cidoc-crm/P141i_was_assigned_by>/rdf:rest*/rdf:first/<http://www.cidoc-crm.org/cidoc-crm/P141_assigned>/<http://www.cidoc-crm.org/cidoc-crm/P14_carried_out_by> ?sperson
    }
  }
}