prefix schema: <https://schema.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
# select * 
construct {
  ?pl schema:name ?placeLabel
}
where {
  ?pl a schema:Person
  service <https://api.rkd.triply.cc/datasets/rkd/RKD-SDO-Knowledge-Graph/services/Virtuoso/sparql> {
      ?pl schema:name ?placeLabel;
      FILTER (lang(?placeLabel) = "nl")
    }
}