prefix schema: <https://schema.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
# select * 
construct {
  ?pl schema:name ?placeLabel
}
where {
  ?pl a schema:Place
  service <https://query.wikidata.org/sparql> {
      ?pl rdfs:label ?placeLabel.
      FILTER (lang(?placeLabel) = "nl")
    }
}